version: '3.7'

services:
  bot:
    image: bot
    container_name: bot
    build:
      context: ..
      dockerfile: docker/bot.dockerfile
    restart: unless-stopped
    env_file: ../.env
    tty: true
    volumes:
      - ../logs:/bot/logs
    command: poetry run python run.py
